services:
  api:
    image: api
    container_name: api
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_ENVIRONMENT=Development
    ports:
      - "5285:8080"
      - "7283:8081"

  database:
    image: postgres:16
    container_name: database
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: mental-health
    volumes:
      - ./containers/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cache:
    image: redis:7.4.1-alpine
    restart: always
    container_name: cache
    ports:
      - "6379:6379"
        
  # comment out the following lines if you do frontend development
  frontend:
    image: frontend
    container_name: frontend
    build:
        context: ../fe-mental-health-chat
        dockerfile: ../fe-mental-health-chat/Dockerfile
    ports:
      - "4200:4200"